version: '3'

services:
  python-service:
    build: ./microservices/python
    volumes:
      - ./microservices/python:/usr/src/app
    ports:
      - 5001:80

  golang-service:
    build: ./microservices/golang
    volumes:
      - ./microservices/golang:/go/src/go-with-compose
    working_dir: /go/src/go-with-compose
  
  website:
    image: php:apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - python-service
      - golang-service
